name: Format checks
description: Run prettier checks over codebase

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: Cache NPM
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-checkout-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-checkout-

    - name: Install prettier and run it
      run: |
        npm install prettier -g
        prettier --config ${{ github.action_path }}/.prettierrc --check "./**/*.{ts,js}"
      shell: bash
      working-directory: "./"
